out_dir: 
name: 
resume: False
# run: 0

data:
    data_dir: 
    splits:
        train: "triplets_train"
        val: "triplets_val"
        test: "evaluation" 

model:
    params:
        base_model: 
        version: 
        weights: 
    freeze: 
        encoder: 

# loss:
#     params:
    
optimizer:
    lr: 
    betas: 
    weight_decay: 

lr_schedular:
    params:
        T_max: 
        eta_min: 
    warmup: 

train:
    loader_params:
        batch_size: 
        shuffle: 
        num_workers: 
    epochs: 

val:
    loader_params:
            batch_size: 
            shuffle: 
            num_workers: 

# test:
#     frequency: 1