out_dir: /home/avishka/muditha/contra_classi/logs
name: ld_contrastive_convnext_pet
resume: False
# run: 0

data:
    target: src.dataset.TripletDataset
    data_dir: "/home/avishka/muditha/contra_classi/data/annots"
    splits:
        train: "low_data_pet_triplet_train"
        val: "low_data_pet_triplet_val"
        test: "low_data_pet_test" 

model:
    target: src.model.TripletModel
    params:
        base_model: "convnext_tiny"
        version: "fb_in22k"
        # weights: 
    freeze: 
        encoder: False

loss:
    target: src.cost.TripletLoss
    
optimizer:
    lr: 0.00005
    betas: [0.9, 0.999]
    weight_decay: 1.0e-6

lr_schedular:
    params:
        T_max: 100
        eta_min: 0.000005
    warmup: 10

train:
    loader_params:
        batch_size: 64
        shuffle: True
        num_workers: 8
    epochs: 100

val:
    loader_params:
            batch_size: 4
            shuffle: False
            num_workers: 8

# test:
#     frequency: 1
