out_dir: /home/avishka/muditha/contra_classi/logs
name: contrastive_convnext_micro
resume: False
# run: 0

data:
    data_dir: "/home/avishka/muditha/contra_classi/data/annots"
    splits:
        train: "micro_triplet_train"
        val: "micro_triplet_val"
        test: "micro_test" 

model:
    params:
        base_model: "convnext_tiny"
        version: "fb_in22k"
        # weights: 
    freeze: 
        encoder: False

# loss:
#     params:
    
optimizer:
    lr: 0.00005
    betas: [0.9, 0.999]
    weight_decay: 1.0e-6

lr_schedular:
    params:
        T_max: 100
        eta_min: 0.000005
    warmup: 10

train:
    loader_params:
        batch_size: 32
        shuffle: True
        num_workers: 8
    epochs: 100

val:
    loader_params:
            batch_size: 16
            shuffle: False
            num_workers: 8

# test:
#     frequency: 1
